-- Pack 1 global daily-challenge leaderboard.
-- Run in a dedicated Supabase project, then enable Anonymous Sign-Ins.

create table if not exists public.pack1_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  challenge_date date not null,
  set_id text not null,
  mode text not null,
  score smallint not null,
  grade text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint pack1_scores_name_check check (char_length(btrim(display_name)) between 2 and 24),
  constraint pack1_scores_set_check check (set_id ~ '^[a-z0-9_-]{2,24}$'),
  constraint pack1_scores_mode_check check (mode in ('top3', 'full')),
  constraint pack1_scores_score_check check (score between 0 and 100),
  constraint pack1_scores_grade_check check (char_length(grade) between 1 and 3),
  constraint pack1_scores_one_ranked_attempt unique (user_id, challenge_date, set_id, mode)
);

create index if not exists pack1_scores_board_idx
  on public.pack1_scores (challenge_date desc, set_id, mode, score desc);
create index if not exists pack1_scores_user_idx
  on public.pack1_scores (user_id, challenge_date desc);

alter table public.pack1_scores enable row level security;
revoke all on table public.pack1_scores from anon, authenticated;

create or replace function public.pack1_submit_score(
  p_set_id text,
  p_mode text,
  p_score integer,
  p_grade text,
  p_challenge_date date,
  p_display_name text,
  p_details jsonb default '{}'::jsonb
)
returns table (
  accepted boolean,
  challenge_date date,
  set_id text,
  mode text,
  score integer,
  grade text,
  display_name text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_inserted boolean := false;
  v_name text := regexp_replace(btrim(coalesce(p_display_name, '')), '\s+', ' ', 'g');
  v_row public.pack1_scores%rowtype;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_challenge_date <> (now() at time zone 'utc')::date then
    raise exception 'Only today''s Daily Challenge can be ranked';
  end if;
  if p_mode not in ('top3', 'full') then
    raise exception 'Invalid mode';
  end if;
  if p_score < 0 or p_score > 100 then
    raise exception 'Invalid score';
  end if;
  if p_set_id is null or p_set_id !~ '^[a-z0-9_-]{2,24}$' then
    raise exception 'Invalid set';
  end if;
  if char_length(v_name) < 2 or char_length(v_name) > 24 then
    raise exception 'Display name must be 2-24 characters';
  end if;

  insert into public.pack1_scores (user_id, display_name, challenge_date, set_id, mode, score, grade, details)
  values (v_user_id, v_name, p_challenge_date, p_set_id, p_mode, p_score, left(coalesce(p_grade, '?'), 3), coalesce(p_details, '{}'::jsonb))
  on conflict (user_id, challenge_date, set_id, mode) do nothing
  returning * into v_row;

  if found then
    v_inserted := true;
  else
    select * into v_row
    from public.pack1_scores s
    where s.user_id = v_user_id
      and s.challenge_date = p_challenge_date
      and s.set_id = p_set_id
      and s.mode = p_mode;
  end if;

  return query select
    v_inserted,
    v_row.challenge_date,
    v_row.set_id,
    v_row.mode,
    v_row.score::integer,
    v_row.grade,
    v_row.display_name;
end;
$$;

create or replace function public.pack1_leaderboard(
  p_period text default 'daily',
  p_set_id text default null,
  p_mode text default 'top3',
  p_limit integer default 50
)
returns table (
  rank bigint,
  display_name text,
  points bigint,
  average_score numeric,
  plays bigint,
  perfects bigint,
  is_me boolean
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with bounds as (
    select
      case p_period
        when 'daily' then (now() at time zone 'utc')::date
        when 'weekly' then date_trunc('week', now() at time zone 'utc')::date
        when 'monthly' then date_trunc('month', now() at time zone 'utc')::date
        when 'all' then date '1970-01-01'
        else (now() at time zone 'utc')::date
      end as start_date
  ), filtered as (
    select s.*
    from public.pack1_scores s, bounds b
    where s.challenge_date >= b.start_date
      and s.mode = case when p_mode in ('top3', 'full') then p_mode else 'top3' end
      and (p_set_id is null or s.set_id = p_set_id)
  ), grouped as (
    select
      user_id,
      (array_agg(display_name order by created_at desc))[1] as display_name,
      sum(score)::bigint as points,
      round(avg(score)::numeric, 1) as average_score,
      count(*)::bigint as plays,
      count(*) filter (where score = 100)::bigint as perfects
    from filtered
    group by user_id
  ), ranked as (
    select
      dense_rank() over (order by points desc, average_score desc, plays desc) as rank,
      display_name,
      points,
      average_score,
      plays,
      perfects,
      user_id = auth.uid() as is_me
    from grouped
  )
  select rank, display_name, points, average_score, plays, perfects, is_me
  from ranked
  order by rank, display_name
  limit greatest(1, least(coalesce(p_limit, 50), 100));
$$;

revoke all on function public.pack1_submit_score(text, text, integer, text, date, text, jsonb) from public, anon;
grant execute on function public.pack1_submit_score(text, text, integer, text, date, text, jsonb) to authenticated;

revoke all on function public.pack1_leaderboard(text, text, text, integer) from public;
grant execute on function public.pack1_leaderboard(text, text, text, integer) to anon, authenticated;
