export const ACQUISITION_PATTERN=/^[a-z0-9][a-z0-9_-]{0,39}$/;
export const CAMPAIGN_SLUG_MAX_LENGTH=64;
export const CAMPAIGN_SLUG_PATTERN=/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;
export const SUPPORTED_CAMPAIGN_DESTINATIONS=Object.freeze(['/']);
export const CREATOR_CAMPAIGN_DESTINATION_PATTERN=/^\/\?game=draft-run&creator=[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
export const isSupportedCampaignDestination=value=>SUPPORTED_CAMPAIGN_DESTINATIONS.includes(value)||CREATOR_CAMPAIGN_DESTINATION_PATTERN.test(value);
export const PACK_ONE_ORIGIN='https://packone.pro';
export const GENERATED_CAMPAIGN_MARKER='<!-- Generated by scripts/generate-campaign-links.mjs. Do not edit by hand. -->';

export const canonicalizeAcquisitionInput=input=>String(input??'').trim().toLowerCase();

export function normalizeAcquisitionValue(input) {
  const normalized=canonicalizeAcquisitionInput(input);
  return ACQUISITION_PATTERN.test(normalized)?normalized:null;
}

export function isCanonicalAcquisitionValue(input) {
  if(typeof input!=='string')return false;
  const normalized=normalizeAcquisitionValue(input);
  return normalized!==null&&input===normalized;
}

export const canonicalizeCampaignSlug=input=>String(input??'').trim().toLowerCase();

export function normalizeCampaignSlug(input) {
  const normalized=canonicalizeCampaignSlug(input);
  return normalized.length<=CAMPAIGN_SLUG_MAX_LENGTH&&CAMPAIGN_SLUG_PATTERN.test(normalized)?normalized:null;
}

export function isCanonicalCampaignSlug(input) {
  if(typeof input!=='string')return false;
  const normalized=normalizeCampaignSlug(input);
  return normalized!==null&&input===normalized;
}

function validateCampaignTrackingFields(entry,label='campaign link') {
  if(!entry||typeof entry!=='object'||Array.isArray(entry))throw new Error(`${label} must be an object.`);
  if(!isSupportedCampaignDestination(entry.destination))throw new Error(`${label} destination "${entry.destination}" is not supported.`);
  for(const key of ['source','campaign']) {
    if(!isCanonicalAcquisitionValue(entry[key]))throw new Error(`${label} ${key} must already be canonical and match ${ACQUISITION_PATTERN}.`);
  }
  if(Object.hasOwn(entry,'medium')&&!isCanonicalAcquisitionValue(entry.medium))throw new Error(`${label} medium must already be canonical and match ${ACQUISITION_PATTERN}.`);
  return {
    destination:entry.destination,
    source:entry.source,
    campaign:entry.campaign,
    ...(Object.hasOwn(entry,'medium')?{medium:entry.medium}:{})
  };
}

export function validateCampaignEntries(input) {
  if(!Array.isArray(input))throw new Error('campaign-links.json must contain an array.');
  const seen=new Set();
  const allowedKeys=new Set(['slug','destination','source','campaign','medium','social_title','social_description']);
  return input.map((entry,index)=>{
    const label=`campaign-links.json entry ${index+1}`;
    if(!entry||typeof entry!=='object'||Array.isArray(entry))throw new Error(`${label} must be an object.`);
    const unknown=Object.keys(entry).filter(key=>!allowedKeys.has(key));
    if(unknown.length)throw new Error(`${label} contains unsupported field(s): ${unknown.join(', ')}.`);
    if(!isCanonicalCampaignSlug(entry.slug))throw new Error(`${label} slug must be canonical lowercase ASCII, 1-${CAMPAIGN_SLUG_MAX_LENGTH} characters, with only letters, digits, and internal hyphens.`);
    if(seen.has(entry.slug))throw new Error(`${label} duplicates slug "${entry.slug}".`);
    seen.add(entry.slug);
    const tracking=validateCampaignTrackingFields(entry,label);
    const social={};
    for(const [key,max] of [['social_title',160],['social_description',280]]) {
      if(!Object.hasOwn(entry,key))continue;
      if(typeof entry[key]!=='string'||!entry[key].trim()||entry[key]!==entry[key].trim()||entry[key].length>max||/[\u0000-\u001f\u007f]/.test(entry[key]))
        throw new Error(`${label} ${key} must be a trimmed printable string of at most ${max} characters.`);
      social[key]=entry[key];
    }
    if(Object.hasOwn(social,'social_description')&&!Object.hasOwn(social,'social_title'))
      throw new Error(`${label} social_description requires social_title.`);
    return {slug:entry.slug,...tracking,...social};
  });
}

export function buildCampaignTrackingUrl(entry) {
  const valid=validateCampaignTrackingFields(entry);
  const url=new URL(valid.destination,PACK_ONE_ORIGIN);
  url.searchParams.set('utm_source',valid.source);
  url.searchParams.set('utm_campaign',valid.campaign);
  if(valid.medium)url.searchParams.set('utm_medium',valid.medium);
  return url.toString();
}

export function buildCampaignVanityUrl(slug) {
  if(!isCanonicalCampaignSlug(slug))throw new Error('Campaign slug must be canonical before building a vanity URL.');
  return `${PACK_ONE_ORIGIN}/go/${slug}/`;
}

export function buildCampaignDraft(input={}) {
  const normalized={
    slug:canonicalizeCampaignSlug(input.slug),
    destination:String(input.destination??'/').trim(),
    source:canonicalizeAcquisitionInput(input.source),
    campaign:canonicalizeAcquisitionInput(input.campaign),
    medium:canonicalizeAcquisitionInput(input.medium)
  };
  const errors={};
  const slug=normalizeCampaignSlug(input.slug);
  if(normalized.slug&&!slug)errors.slug=`Use 1-${CAMPAIGN_SLUG_MAX_LENGTH} lowercase letters/digits with internal hyphens only.`;
  if(!isSupportedCampaignDestination(normalized.destination))errors.destination='Choose a supported destination.';
  if(!normalizeAcquisitionValue(input.source))errors.source='Use 1-40 letters, digits, underscores, or hyphens; spaces and slashes are not allowed.';
  if(!normalizeAcquisitionValue(input.campaign))errors.campaign='Use 1-40 letters, digits, underscores, or hyphens; spaces and slashes are not allowed.';
  if(normalized.medium&&!normalizeAcquisitionValue(input.medium))errors.medium='Use 1-40 letters, digits, underscores, or hyphens; spaces and slashes are not allowed.';
  const trackingValid=!errors.destination&&!errors.source&&!errors.campaign&&!errors.medium;
  const tracking=trackingValid?{
    destination:normalized.destination,
    source:normalized.source,
    campaign:normalized.campaign,
    ...(normalized.medium?{medium:normalized.medium}:{})
  }:null;
  const valid=trackingValid&&Boolean(slug);
  const socialTitle=String(input.social_title??'').trim();
  const socialDescription=String(input.social_description??'').trim();
  if(socialTitle&&(socialTitle.length>160||/[\u0000-\u001f\u007f]/.test(socialTitle)))errors.social_title='Use a short printable social title.';
  if(socialDescription&&(socialDescription.length>280||/[\u0000-\u001f\u007f]/.test(socialDescription)))errors.social_description='Use a short printable social description.';
  if(socialDescription&&!socialTitle)errors.social_description='A social description requires a social title.';
  const entry=valid&&!errors.social_title&&!errors.social_description
    ? {slug:normalized.slug,...tracking,...(socialTitle?{social_title:socialTitle}:{}),...(socialDescription?{social_description:socialDescription}:{})}
    : null;
  return {
    valid,
    trackingValid,
    errors,
    normalized,
    entry,
    vanityUrl:slug?buildCampaignVanityUrl(normalized.slug):'',
    trackedUrl:tracking?buildCampaignTrackingUrl(tracking):''
  };
}

const htmlEscape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

export function renderCampaignRedirectPage(entry) {
  const valid=validateCampaignEntries([entry])[0];
  const trackedUrl=buildCampaignTrackingUrl(valid);
  const trackedHref=htmlEscape(trackedUrl);
  const title=valid.social_title||'Pack One: Daily MTG Draft Decisions';
  const description=valid.social_description||'Eight real MTG draft decisions every day. Make your pick, then compare with a trophy drafter.';
  const socialRoute=Boolean(valid.social_title);
  const socialUrl=socialRoute?buildCampaignVanityUrl(valid.slug):'https://packone.pro/';
  const escapedTitle=htmlEscape(title),escapedDescription=htmlEscape(description),escapedSocialUrl=htmlEscape(socialUrl);
  return `${GENERATED_CAMPAIGN_MARKER}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="${escapedDescription}" />
  <meta name="robots" content="noindex,nofollow" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="${escapedTitle}" />
  <meta property="og:description" content="${escapedDescription}" />
  <meta property="og:url" content="${escapedSocialUrl}" />
  <meta property="og:image" content="https://packone.pro/social-preview-v3.jpg" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content="${escapedTitle}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escapedTitle}" />
  <meta name="twitter:description" content="${escapedDescription}" />
  <meta name="twitter:image" content="https://packone.pro/social-preview-v3.jpg" />
  <meta name="twitter:image:alt" content="${escapedTitle}" />
  <link rel="canonical" href="${escapedSocialUrl}" />
  <title>${escapedTitle}</title>
  <script>location.replace(${JSON.stringify(trackedUrl)});</script>
</head>
<body>
  <p>Redirecting to Pack One. <a href="${trackedHref}">Continue to Pack One</a>.</p>
</body>
</html>
`;
}
