export const ACQUISITION_PATTERN=/^[a-z0-9][a-z0-9_-]{0,39}$/;
export const CAMPAIGN_SLUG_MAX_LENGTH=64;
export const CAMPAIGN_SLUG_PATTERN=/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;
export const SUPPORTED_CAMPAIGN_DESTINATIONS=Object.freeze(['/']);
export const PACK_ONE_ORIGIN='https://packone.pro';
export const GENERATED_CAMPAIGN_MARKER='<!-- Generated by scripts/generate-campaign-links.mjs. Do not edit by hand. -->';

export const canonicalizeAcquisitionInput=input=>String(input??'').trim().toLowerCase();

export function normalizeAcquisitionValue(input) {
  const normalized=canonicalizeAcquisitionInput(input);
  return ACQUISITION_PATTERN.test(normalized)?normalized:null;
}

export function isCanonicalAcquisitionValue(input) {
  if(typeof input!=='string')return false;
  const normalized=normalizeAcquisitionValue(input);
  return normalized!==null&&input===normalized;
}

export const canonicalizeCampaignSlug=input=>String(input??'').trim().toLowerCase();

export function normalizeCampaignSlug(input) {
  const normalized=canonicalizeCampaignSlug(input);
  return normalized.length<=CAMPAIGN_SLUG_MAX_LENGTH&&CAMPAIGN_SLUG_PATTERN.test(normalized)?normalized:null;
}

export function isCanonicalCampaignSlug(input) {
  if(typeof input!=='string')return false;
  const normalized=normalizeCampaignSlug(input);
  return normalized!==null&&input===normalized;
}

export function validateCampaignEntries(input) {
  if(!Array.isArray(input))throw new Error('campaign-links.json must contain an array.');
  const seen=new Set();
  const allowedKeys=new Set(['slug','destination','source','campaign','medium']);
  return input.map((entry,index)=>{
    const label=`campaign-links.json entry ${index+1}`;
    if(!entry||typeof entry!=='object'||Array.isArray(entry))throw new Error(`${label} must be an object.`);
    const unknown=Object.keys(entry).filter(key=>!allowedKeys.has(key));
    if(unknown.length)throw new Error(`${label} contains unsupported field(s): ${unknown.join(', ')}.`);
    if(!isCanonicalCampaignSlug(entry.slug))throw new Error(`${label} slug must be canonical lowercase ASCII, 1-${CAMPAIGN_SLUG_MAX_LENGTH} characters, with only letters, digits, and internal hyphens.`);
    if(seen.has(entry.slug))throw new Error(`${label} duplicates slug "${entry.slug}".`);
    seen.add(entry.slug);
    if(!SUPPORTED_CAMPAIGN_DESTINATIONS.includes(entry.destination))throw new Error(`${label} destination "${entry.destination}" is not supported.`);
    for(const key of ['source','campaign']) {
      if(!isCanonicalAcquisitionValue(entry[key]))throw new Error(`${label} ${key} must already be canonical and match ${ACQUISITION_PATTERN}.`);
    }
    if(Object.hasOwn(entry,'medium')&&!isCanonicalAcquisitionValue(entry.medium))throw new Error(`${label} medium must already be canonical and match ${ACQUISITION_PATTERN}.`);
    return {
      slug:entry.slug,
      destination:entry.destination,
      source:entry.source,
      campaign:entry.campaign,
      ...(Object.hasOwn(entry,'medium')?{medium:entry.medium}:{})
    };
  });
}

export function buildCampaignTrackingUrl(entry) {
  const valid=validateCampaignEntries([entry])[0];
  const url=new URL(valid.destination,PACK_ONE_ORIGIN);
  url.searchParams.set('utm_source',valid.source);
  url.searchParams.set('utm_campaign',valid.campaign);
  if(valid.medium)url.searchParams.set('utm_medium',valid.medium);
  return url.toString();
}

export function buildCampaignVanityUrl(slug) {
  if(!isCanonicalCampaignSlug(slug))throw new Error('Campaign slug must be canonical before building a vanity URL.');
  return `${PACK_ONE_ORIGIN}/go/${slug}/`;
}

export function buildCampaignDraft(input={}) {
  const normalized={
    slug:canonicalizeCampaignSlug(input.slug),
    destination:String(input.destination??'/').trim(),
    source:canonicalizeAcquisitionInput(input.source),
    campaign:canonicalizeAcquisitionInput(input.campaign),
    medium:canonicalizeAcquisitionInput(input.medium)
  };
  const errors={};
  if(!normalizeCampaignSlug(input.slug))errors.slug=`Use 1-${CAMPAIGN_SLUG_MAX_LENGTH} lowercase letters/digits with internal hyphens only.`;
  if(!SUPPORTED_CAMPAIGN_DESTINATIONS.includes(normalized.destination))errors.destination='Choose a supported destination.';
  if(!normalizeAcquisitionValue(input.source))errors.source='Use 1-40 letters, digits, underscores, or hyphens; spaces and slashes are not allowed.';
  if(!normalizeAcquisitionValue(input.campaign))errors.campaign='Use 1-40 letters, digits, underscores, or hyphens; spaces and slashes are not allowed.';
  if(normalized.medium&&!normalizeAcquisitionValue(input.medium))errors.medium='Use 1-40 letters, digits, underscores, or hyphens; spaces and slashes are not allowed.';
  const valid=Object.keys(errors).length===0;
  const entry=valid?{
    slug:normalized.slug,
    destination:normalized.destination,
    source:normalized.source,
    campaign:normalized.campaign,
    ...(normalized.medium?{medium:normalized.medium}:{})
  }:null;
  return {
    valid,
    errors,
    normalized,
    entry,
    vanityUrl:normalizeCampaignSlug(input.slug)?buildCampaignVanityUrl(normalized.slug):'',
    trackedUrl:entry?buildCampaignTrackingUrl(entry):''
  };
}

const htmlEscape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

export function renderCampaignRedirectPage(entry) {
  const valid=validateCampaignEntries([entry])[0];
  const trackedUrl=buildCampaignTrackingUrl(valid);
  const trackedHref=htmlEscape(trackedUrl);
  const title='Pack One: Learn from trophy drafts';
  const description='Learn from trophy drafts. Eight picks. Your call.';
  return `${GENERATED_CAMPAIGN_MARKER}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Pack One: Learn from trophy drafts. Eight picks. Your call." />
  <meta name="robots" content="noindex,nofollow" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="${title}" />
  <meta property="og:description" content="${description}" />
  <meta property="og:url" content="https://packone.pro/" />
  <meta property="og:image" content="https://packone.pro/mobile/assets/images/icon.png" />
  <meta property="og:image:width" content="1024" />
  <meta property="og:image:height" content="1024" />
  <meta property="og:image:alt" content="Pack One" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${title}" />
  <meta name="twitter:description" content="${description}" />
  <meta name="twitter:image" content="https://packone.pro/mobile/assets/images/icon.png" />
  <meta name="twitter:image:alt" content="Pack One" />
  <link rel="canonical" href="https://packone.pro/" />
  <title>${title}</title>
  <script>location.replace(${JSON.stringify(trackedUrl)});</script>
</head>
<body>
  <p>Redirecting to Pack One. <a href="${trackedHref}">Continue to Pack One</a>.</p>
</body>
</html>
`;
}
