import {storedAccountToken,signInAccount,signUpAccount,signOutAccount} from '../growth-api.mjs';
const root=document.querySelector('#admin');
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const fmt=x=>x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:1});
const pct=x=>x==null?'—':`${fmt(x)}%`;
const base=window.PACK1_API.draftRunUrl;
let report,params=new URLSearchParams(),invite=null;
const hash=new URLSearchParams(location.hash.slice(1));
if(hash.has('invite')){invite=hash.get('invite');sessionStorage.setItem('pack1-admin-invite',invite);history.replaceState({},'',location.pathname);}
invite=invite||sessionStorage.getItem('pack1-admin-invite');
async function request(path,body) {
  const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'content-type':'application/json','x-pack1-auth-session':storedAccountToken()||''},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(45000)});
  const d=await r.json();if(!r.ok)throw Object.assign(Error(d.error||'Report unavailable.'),{status:r.status});return d;
}
function login(message='') {
  root.innerHTML=`<section class="login"><h1>Decision quality</h1><p>${invite?'Your private invitation is ready. Sign in, or create your admin account below.':'Sign in with the account granted admin access.'}</p><form id="login"><label>Name<input name="name" autocomplete="name"></label><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" minlength="8" required></label><label>Setup code (first visit only)<input name="invite" autocomplete="off" spellcheck="false" value="${esc(invite||'')}" placeholder="Paste your private setup code"></label><div class="actions"><button type="submit">Sign in</button><button type="submit" name="create" value="yes" class="secondary">Create account</button></div></form><p id="status" class="error" role="alert">${esc(message)}</p><a href="/">Back to Pack One</a></section>`;
  document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));form.querySelectorAll('button').forEach(b=>b.disabled=true);try{if(data.invite){if(!/^[a-f0-9]{64}$/.test(data.invite))throw Error('The setup code must contain 64 letters and numbers.');invite=data.invite;sessionStorage.setItem('pack1-admin-invite',invite);}if(e.submitter?.name==='create')await signUpAccount({...data,name:data.name||'Pack One Admin'});else await signInAccount(data);await load();}catch(err){document.querySelector('#status').textContent=err.message;}finally{form.querySelectorAll('button').forEach(b=>b.disabled=false);}};
}
function options(values,current){return values.map(([v,label])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label)}</option>`).join('');}
function table(rows,label) {
  return `<div class="scroll"><table><thead><tr><th>${label}</th><th>Answers</th><th>Trophy match</th><th>Avg. partial</th><th>Median time</th><th>Rerolls / views</th><th>Likely left / mature views</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.label)}${Number(r.answers)<30?' · early':''}</td><td>${fmt(r.answers)}</td><td>${pct(r.trophy_match_pct)}<div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(r.trophy_match_pct)||0))}%"></i></div></td><td>${fmt(r.average_partial_credit)}</td><td>${r.median_seconds==null?'—':fmt(r.median_seconds)+'s'} <small>n=${fmt(r.timed_answers)}</small></td><td>${fmt(r.rerolls)} / ${fmt(r.exposures)}</td><td>${fmt(r.likely_abandoned)} / ${fmt(r.mature_exposures)}</td></tr>`).join('')||'<tr><td colspan="7">No player observations in this range yet.</td></tr>'}</tbody></table></div>`;
}
function render() {
  const s=report.summary,c=report.coverage,f=report.filters;
  root.innerHTML=`<h1>How the decisions play</h1><p class="muted">First encounters · QA excluded · Updated ${esc(new Date(report.generated_at).toLocaleString())}</p>
    <form id="filters" class="filters"><label>From<input type="date" name="from" value="${f.start}" required></label><label>Through<input type="date" name="to" value="${f.end}" required></label><label>Environment<select name="environment">${options([['all','All'],['mixed','Regular'],['powered-cube','Powered Cube']],f.environment)}</select></label><label>Run type<select name="type">${options([['all','All'],['daily','Daily'],['practice','Practice'],['challenge','Challenge']],f.type)}</select></label><label>Set<select name="set">${options([['all','All'],...report.sets.map(x=>[x,x==='powered-cube'?'Powered Cube':x.toUpperCase()])],f.set)}</select></label><label>Difficulty<select name="difficulty">${options([['all','All'],['easy','Easy'],['medium','Medium'],['hard','Hard']],f.band)}</select></label><label>Draft pick<select name="pick">${options([['all','All'],...Array.from({length:12},(_,i)=>[String(i+1),'P1P'+(i+1)])],f.pick)}</select></label><label>Selection version<select name="version">${options([['all','All'],...Array.from(new Set(report.groups.filter(r=>r.dimension==='version').map(r=>r.label.split(' / ')[0]))).map(x=>[x,x]),...(f.version!=='all'&&!report.groups.some(r=>r.dimension==='version'&&r.label.startsWith(f.version+' / '))?[[f.version,f.version]]:[])],f.version)}</select></label><button>Refresh</button><button type="button" class="secondary" id="csv">Export CSV</button><button type="button" class="secondary" id="signout">Sign out</button></form>
    <div class="cards">${[['First-encounter answers',fmt(s.answers)],['Trophy match rate',pct(s.trophy_match_pct)],['Average alternative credit',fmt(s.average_partial_credit)],['Median foreground time',s.median_seconds==null?'—':fmt(s.median_seconds)+'s'],['Players',fmt(s.players)],['Completed / observed runs',`${fmt(s.completed_runs)} / ${fmt(s.runs)}`],['Rerolls / viewed choices',`${fmt(s.rerolls)} / ${fmt(s.exposures)}`],['Likely abandonment',fmt(s.likely_abandoned)]].map(([label,value])=>`<div class="card"><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>
    <p class="note">${Number(s.answers)<30?'Early data: wait for more player answers before drawing conclusions. ':''}Difficulty is a model estimate, not a measured human success probability. “Likely abandonment” means an unfinished choice with 24 hours of inactivity; returning players leave that count.</p>
    <p class="muted">Excluded: ${fmt(c.qa_excluded)} QA observations, ${fmt(c.repeats_excluded)} repeat encounters, ${fmt(c.unobserved_excluded)} outcomes without a recorded view. Pending choices: ${fmt(s.pending)}. Timing available for ${fmt(s.timed_answers)} answers; reloads and multiple tabs omit timing. P90: ${s.p90_seconds==null?'—':fmt(s.p90_seconds)+'s'}.</p>
    ${[['difficulty','By difficulty'],['pick','By real draft pick'],['round','By game position'],['set','By set'],['model_disagreement','When the model questions the trophy pick'],['version','By scoring and selection version']].map(([dimension,title])=>`<h2>${title}</h2>${table(report.groups.filter(r=>r.dimension===dimension).sort((a,b)=>dimension==='difficulty'?['easy','medium','hard','unrated'].indexOf(a.label)-['easy','medium','hard','unrated'].indexOf(b.label):a.label.localeCompare(b.label,undefined,{numeric:true})),dimension==='model_disagreement'?'Disagreement':'Group')}`).join('')}
    <h2>Alternative-credit distribution</h2><p>${[['0–24',s.partial_0_24],['25–49',s.partial_25_49],['50–74',s.partial_50_74],['75–95',s.partial_75_95]].map(([label,n])=>`${label} points: <strong>${fmt(n)}</strong>`).join(' · ')}</p>
    <h2>Decisions to review</h2><p class="muted">At least five first-encounter answers. Model disagreements appear first, then the largest samples. Small samples are exploratory.</p><div id="reviews">${report.reviews.map(r=>`<details class="review" data-puzzle="${esc(r.puzzle_id)}"><summary>${esc(r.set_id.toUpperCase())} · P1P${r.pick_number} · ${fmt(r.answers)} answers · ${pct(r.trophy_match_pct)} trophy matches${r.model_disagreement===true||r.model_disagreement==='t'?' · model disagreement':''}</summary><div class="detail"></div></details>`).join('')||'<p>No decisions have five qualifying answers yet.</p>'}</div><p id="status" role="status"></p>`;
  document.querySelector('#filters').onsubmit=async e=>{e.preventDefault();params=new URLSearchParams(new FormData(e.currentTarget));await load();};
  document.querySelector('#signout').onclick=async()=>{await signOutAccount();login();};
  document.querySelector('#csv').onclick=()=>{
    const rows=report.groups,keys=rows.length?Object.keys(rows[0]):['dimension','label','answers'];
    const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
    const blob=new Blob([[keys,...rows.map(r=>keys.map(k=>r[k]))].map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv'});
    const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pack-one-decisions-${f.start}-${f.end}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
  };
  document.querySelectorAll('[data-puzzle]').forEach(el=>el.ontoggle=async()=>{if(!el.open||el.dataset.loaded)return;const target=el.querySelector('.detail');target.textContent='Loading decision…';try{const data=await request(`/v1/admin/decisions/${el.dataset.puzzle}?${params}`),p=data.puzzle;target.innerHTML=`<p>Earlier picks: ${esc(p.prior_picks.map(c=>c.name).join(', ')||'None')}</p><div class="decision-cards">${p.candidates.map(card=>{const count=data.choices.find(c=>c.selected_id===card.id);return `<article>${/^https:\/\//.test(card.image_url||'')?`<img src="${esc(card.image_url)}" alt="${esc(card.name)}" loading="lazy">`:''}<p><strong>${esc(card.name)}</strong>${card.id===p.historical_pick_id?' · Trophy pick':''}<br>${fmt(count?.answers||0)} choices · Model support ${pct(100*card.model_probability)}<br>Average awarded: ${fmt(count?.average_score)}</p></article>`;}).join('')}</div>`;el.dataset.loaded='1';}catch(err){target.textContent=err.message;}});
}
async function load() {
  if(!storedAccountToken()){login();return;}
  try{if(invite){await request('/v1/admin/claim',{invite});sessionStorage.removeItem('pack1-admin-invite');invite=null;}report=await request('/v1/admin/measurements?'+params);render();}
  catch(err){if(err.status===401||err.status===403){login(err.message);return;}const status=document.querySelector('#status');if(status)status.textContent=err.message;else root.innerHTML=`<h1>Report unavailable</h1><p class="error">${esc(err.message)}</p><button id="retry">Try again</button>`;document.querySelector('#retry')?.addEventListener('click',load);}
}
await load();
