const esc=x=>String(x??'—').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const yes=x=>x===true||x==='t';
const date=x=>x?new Date(x).toLocaleString():'Not recorded';
export async function renderCorpus(root,request) {
 const data=await request('/v1/admin/corpus');
 root.innerHTML=`<h1>Corpus operations</h1><p>Serving corpus: <strong>${esc(data.corpus_version)}</strong>. Changes affect newly generated games. Created Dailies, shared runs and results retain their decisions.</p><p id="corpus-status" role="status"></p>
 <div class="corpus-grid">${data.sets.map((s,i)=>{const m=s.manifest||{},f=m.full_import||{},q=s.report?.metrics||{},fresh=yes(s.health_current),ready=yes(s.ready)&&fresh;return `<article class="corpus-set"><h2>${esc(s.set_name)} <small>${esc(s.set_id.toUpperCase())}</small></h2><p><strong>${esc(s.status||'Awaiting corpus')}</strong> · ${esc(s.source_event_type)} · Released ${esc(s.release_date)}</p>
 <dl>${Object.entries({'Archive':s.archive_available==null?'Not checked':yes(s.archive_available)?'Available':'Unavailable','Archive version':s.archive_etag||f.source_archive?.etag||m.source_archive?.etag,'Archive modified':s.archive_last_modified||f.source_archive?.last_modified||m.source_archive?.last_modified,'Last checked':date(s.last_checked_at),'Source drafts':f.source_drafts,'Qualified drafts':f.qualified_drafts,'Trophy drafts':f.source_trophies??m.trophy_drafts,'Qualified trophies':f.qualified_trophies,'Source trajectories excluded from new play':s.excluded_source_trajectories,'Included trophies':f.included_trophies,'Excluded trophies':f.excluded_trophies,'Usable first-eight decisions':q.usablePuzzles,'All retained decisions in this version':f.total_puzzles??m.puzzles,'Model':f.model_version||m.model_version,'Import':s.import_status||'Historical import; time not recorded','Last successful import':date(s.last_successful_import),'Last health verification':date(s.last_health_verification),'Card metadata coverage':q.metadataCoverage==null?null:`${(100*q.metadataCoverage).toFixed(2)}%`,'Image reference coverage':q.imageCoverage==null?null:`${(100*q.imageCoverage).toFixed(2)}%`}).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>
 ${s.last_error?`<p class="error">${esc(s.last_error)}</p>`:''}<details><summary>Quality gates · ${ready?'Ready':fresh?'Blocked':'Verification required'}</summary><p>Policy ${esc(data.gate_version)}. Publication requires a passing check for the exact current manifest within ${data.thresholds.healthMaxAgeDays} days.</p>${s.report?.gates?.map(g=>`<p class="${g.pass?'':'error'}"><strong>${g.pass?'Pass':'Blocked'}: ${esc(g.id)}</strong><br>${esc(g.requirement)}<br>Observed: ${esc(typeof g.actual==='object'?JSON.stringify(g.actual):g.actual)}</p>`).join('')||'<p>No complete health report is available. Run the Corpus Operations workflow.</p>'}<p>Exclusions: ${esc(JSON.stringify(f.exclusion_reasons||m.exclusions||{}))}</p><p>Puzzles by pick: ${esc(JSON.stringify(q.puzzlesByPick||{}))}</p><p>Trophy outcomes: ${esc(JSON.stringify(f.trophy_outcomes||{}))}</p></details>
 ${s.status&&data.transitions[s.status]?.length?`<form data-set="${i}"><label>Change status<select name="status" required><option value="" selected disabled>Choose a status</option>${data.transitions[s.status].map(x=>`<option value="${x}" ${x==='Live'&&!ready?'disabled':''}>${x}${x==='Live'&&!ready?' — verification required':''}</option>`).join('')}</select></label><label>Reason (optional)<input name="reason" maxlength="1000"></label><button>Apply status</button></form>`:''}</article>`;}).join('')}</div>
 <h2>Additional puzzle sources</h2><p>Each source has its own publication status. The parent set must also be Live for new play. Historical runs retain their decisions.</p>
 <div class="corpus-grid">${(data.components||[]).map((c,i)=>{const ready=yes(c.ready)&&yes(c.health_current),m=c.manifest||{};return `<article class="corpus-set"><h3>${esc(c.set_id.toUpperCase())} · Traditional 3–0</h3><p><strong>${esc(c.status)}</strong> · Premier-trained ${esc(c.model_version)}</p><p>Source revision: ${esc(c.component_version)}<br>Retained decisions: ${esc(m.puzzles)} · Usable: ${esc(c.report?.usable_puzzles)}<br>Last verified: ${esc(date(c.checked_at))}</p><details><summary>${ready?'Ready for publication':'Publication blocked'}</summary><p>Exact frozen Premier support parity and independent puzzle/scoring gates are required. Verification expires after seven days.</p><pre>${esc(JSON.stringify(c.report||{error:'Verification required'},null,2))}</pre></details>${data.transitions[c.status]?.length?`<form data-component="${i}"><label>Change source status<select name="status" required><option value="" selected disabled>Choose a status</option>${data.transitions[c.status].map(x=>`<option value="${x}" ${x==='Live'&&!ready?'disabled':''}>${x}</option>`).join('')}</select></label><label>Reason (optional)<input name="reason" maxlength="1000"></label><button>Apply source status</button></form>`:''}</article>`;}).join('')||'<p>No additional source components have been imported.</p>'}</div>
 ${(data.blocked_sources||[]).map(s=>`<article class="corpus-set"><h3>${esc(s.set_id.toUpperCase())} · ${esc(s.event_type)}</h3><p>Blocked before Candidate</p><p class="error">${esc(s.last_error)}</p></article>`).join('')}
 <h2>Status history</h2><div class="scroll"><table><thead><tr><th>When</th><th>Set</th><th>Change</th><th>Admin account</th><th>Reason</th></tr></thead><tbody>${data.history.map(h=>`<tr><td>${esc(date(h.changed_at))}</td><td>${esc(h.set_id)}${h.component_version?` · ${esc(h.component_version)}`:''}</td><td>${esc(h.old_status)} → ${esc(h.new_status)}</td><td>${esc(h.auth_user_id)}</td><td>${esc(h.reason)}</td></tr>`).join('')||'<tr><td colspan="5">No administrative changes recorded.</td></tr>'}</tbody></table></div>`;
 root.querySelectorAll('[data-set]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const s=data.sets[Number(form.dataset.set)],b=Object.fromEntries(new FormData(form));if(!b.status)return;const button=form.querySelector('button');button.disabled=true;try{await request(`/v1/admin/corpus/${s.set_id}/status`,{...b,oldStatus:s.status,corpusVersion:data.corpus_version});await renderCorpus(root,request);root.querySelector('#corpus-status').textContent=`${s.set_name}: ${b.status}. Existing games are preserved.`;}catch(err){root.querySelector('#corpus-status').textContent=err.message;button.disabled=false;}});
 root.querySelectorAll('[data-component]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const c=data.components[Number(form.dataset.component)],b=Object.fromEntries(new FormData(form));if(!b.status)return;const button=form.querySelector('button');button.disabled=true;try{await request(`/v1/admin/corpus/${c.set_id}/components/${c.component_version}/status`,{...b,oldStatus:c.status,corpusVersion:data.corpus_version});await renderCorpus(root,request);root.querySelector('#corpus-status').textContent=`${c.set_id}: source ${b.status}. Existing games are preserved.`;}catch(err){root.querySelector('#corpus-status').textContent=err.message;button.disabled=false;}});
}
