const esc=x=>String(x??'N/A').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const yes=x=>x===true||x==='t';
const date=x=>x?new Date(x).toLocaleString():'Not recorded';
const count=x=>x==null?'N/A':Number(x).toLocaleString();
const pct=x=>x==null?'N/A':`${(Number(x)*100).toFixed(1)}%`;
const ready=s=>yes(s.ready)&&yes(s.health_current);
const health=s=>ready(s)?'Ready':s.report&&!yes(s.ready)?'Blocked':'Check needed';
const badge=(label,kind=label)=>`<span class="corpus-badge ${esc(String(kind).toLowerCase().replaceAll(' ','-'))}">${esc(label)}</span>`;
function metrics(values){return `<dl class="corpus-metrics">${Object.entries(values).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`;}
function actionForm(s,data,component=false){const choices=data.transitions[s.status]||[];if(!choices.length)return '';return `<form class="corpus-action" data-status-form data-set="${esc(s.set_id)}" ${component?`data-component="${esc(s.component_version)}"`:''}><label>Change status<select name="status" required><option value="" selected disabled>Choose a status</option>${choices.map(x=>`<option value="${x}" ${x==='Live'&&!ready(s)?'disabled':''}>${x}${x==='Live'&&!ready(s)?' (verification required)':''}</option>`).join('')}</select></label><label>Reason (optional)<input name="reason" maxlength="1000"></label><button type="submit">Apply status</button></form>`;}
function snapshotForm(s,data){const choices=(data.snapshots||[]).filter(x=>x.set_id===s.set_id&&x.lifecycle_status==='Candidate'&&!yes(x.active)&&yes(x.ready)&&yes(x.health_current));if(s.status!=='Live'||!choices.length)return '';return `<form class="corpus-action" data-snapshot-form data-set="${esc(s.set_id)}"><label>Activate verified source snapshot<select name="sourceSnapshotId" required><option value="" selected disabled>Choose a snapshot</option>${choices.map(x=>`<option value="${esc(x.source_snapshot_id)}">${esc(x.source_snapshot_id.slice(0,12))} · ${esc(date(x.created_at))}</option>`).join('')}</select></label><label>Reason (optional)<input name="reason" maxlength="1000"></label><button type="submit">Activate snapshot</button></form>`;}
function setDetails(s,data){const m=s.manifest||{},f=m.full_import||{},q=s.report?.metrics||{},components=(data.components||[]).filter(c=>c.set_id===s.set_id);return `
 <div class="corpus-detail-heading"><div><p class="muted">${esc(s.set_id.toUpperCase())} · ${esc(s.source_event_type||'PremierDraft')}</p><h2>${esc(s.set_name)}</h2>${badge(s.status||'Awaiting corpus')} ${badge(health(s))}</div><button type="button" class="secondary" id="close-corpus-detail" aria-label="Close set details">Close</button></div>
 <div class="corpus-detail-summary">${metrics({'Serving decisions':count(s.serving_count),'Below score floor':count(s.under_floor_count),'Retained decisions':count(f.total_puzzles??m.puzzles),'Release date':s.release_date,'Model':f.model_version||m.model_version,'Corpus':s.corpus_version})}</div>
 ${actionForm(s,data)}${snapshotForm(s,data)}${s.last_error?`<p class="error">${esc(s.last_error)}</p>`:''}
 <h3>Quality & coverage</h3><p>Minimum implied trophy score: ${data.minimum_implied_trophy_score??20}. Publication requires current passing evidence for this exact manifest.</p>
 <div class="scroll"><table class="corpus-gates"><thead><tr><th>Gate</th><th>Result</th><th>Requirement / observed</th></tr></thead><tbody>${s.report?.gates?.map(g=>`<tr><td>${esc(g.id)}</td><td>${badge(g.pass?'Pass':'Blocked')}</td><td>${esc(g.requirement)}<small>${esc(typeof g.actual==='object'?JSON.stringify(g.actual):g.actual)}</small></td></tr>`).join('')||'<tr><td colspan="3">No complete report. Run Corpus Operations to verify this set.</td></tr>'}</tbody></table></div>
 ${metrics({'Health checked':date(s.last_health_verification),'Health policy':s.report?.gate_version||data.gate_version,'Metadata complete':pct(q.metadataCoverage),'Image references complete':pct(q.imageCoverage),'Usable decisions by pick':JSON.stringify(s.serving_by_pick||q.puzzlesByPick||{}),'Model validation':q.validation?`Top-1 ${pct(q.validation.top1)} · log loss ${Number(q.validation.logLoss).toFixed(3)} · mean rank ${Number(q.validation.meanRank).toFixed(2)} · ECE ${pct(q.validation.calibrationError)}`:'Not recorded'})}
 <details class="corpus-section"><summary>Archive & import accounting</summary>${metrics({'Archive':s.archive_available==null?'Not checked':yes(s.archive_available)?'Available':'Unavailable','Version / ETag':s.archive_etag||f.source_archive?.etag,'Archive modified':s.archive_last_modified||f.source_archive?.last_modified,'Last checked':date(s.last_checked_at),'Source drafts':count(f.source_drafts),'Qualified drafts':count(f.qualified_drafts),'Trophy drafts':count(f.source_trophies??m.trophy_drafts),'Qualified trophies':count(f.qualified_trophies),'Included trophies':count(f.included_trophies),'Excluded trophies':count(f.excluded_trophies),'Excluded source trajectories':count(s.excluded_source_trajectories),'Exclusion reasons':JSON.stringify(f.exclusion_reasons||m.exclusions||{}),'Audited trophy outcomes':JSON.stringify(q.sourceAudit?.outcomes||f.trophy_outcomes||{}),'Import':s.import_status||'Historical import','Last successful import':date(s.last_successful_import)})}</details>
 ${components.length?`<details class="corpus-section" open><summary>Additional source inventory · ${components.length}</summary>${components.map(c=>`<section class="corpus-component"><h3>Traditional 3–0 ${badge(c.status)}</h3><p>${esc(c.component_version)}</p>${metrics({'Retained decisions':count(c.manifest?.puzzles),'Eligible after score floor':count(c.eligible_count),'Below score floor':count(c.under_floor_count),'Model':c.model_version,'Verified':date(c.checked_at)})}${actionForm(c,data,true)}<details><summary>Admission evidence</summary><pre>${esc(JSON.stringify(c.report||{},null,2))}</pre></details></section>`).join('')}</details>`:''}
 ${(data.blocked_sources||[]).filter(c=>c.set_id===s.set_id).map(c=>`<p class="error">${esc(c.event_type)} blocked before Candidate: ${esc(c.last_error)}</p>`).join('')}
 <details class="corpus-section"><summary>Status history</summary><div class="scroll"><table><thead><tr><th>When</th><th>Change</th><th>Who</th><th>Reason</th></tr></thead><tbody>${data.history.filter(h=>h.set_id===s.set_id).map(h=>`<tr><td>${esc(date(h.changed_at))}</td><td>${esc(h.old_status)} → ${esc(h.new_status)}${h.component_version?`<small>${esc(h.component_version)}</small>`:''}</td><td>${esc(h.auth_user_id||h.admin_identity?.actor||h.admin_identity?.subject)}</td><td>${esc(h.reason)}</td></tr>`).join('')||'<tr><td colspan="4">No status changes recorded.</td></tr>'}</tbody></table></div></details>`;}
export async function renderCorpus(root,request){
 const data=await request('/v1/admin/corpus'),sets=data.sets||[];
 const totals=Object.fromEntries(['Live','Candidate','Paused','Retired'].map(status=>[status,sets.filter(s=>s.status===status).length]));
 root.innerHTML=`<h1>Corpus operations</h1><p class="muted">${esc(data.corpus_version)} · Select a set to inspect quality, provenance and publication controls.</p><div class="corpus-overview">${Object.entries(totals).map(([name,n])=>`<div><strong>${n}</strong><span>${name}</span></div>`).join('')}</div><p id="corpus-status" role="status"></p>
 <div class="filters corpus-filters"><label>Find a set<input type="search" id="corpus-search" placeholder="Name or code"></label><label>Serving status<select id="corpus-filter"><option value="">All statuses</option>${['Live','Candidate','Paused','Retired','Awaiting corpus'].map(s=>`<option>${s}</option>`).join('')}</select></label><label>Quality<select id="corpus-quality"><option value="">All checks</option><option>Ready</option><option>Blocked</option><option>Check needed</option></select></label><span id="corpus-row-count" class="muted" aria-live="polite"></span></div>
 <div class="scroll corpus-table-wrap" tabindex="0" aria-label="Corpus sets; scroll horizontally for all columns"><table class="corpus-table"><thead><tr>${[['set_name','Set'],['status','Status'],['serving_count','Serving'],['under_floor_count','Below 20'],['health','Quality'],['release_date','Release'],['import_status','Import']].map(([key,label])=>`<th scope="col"><button type="button" class="corpus-sort" data-sort="${key}">${label}<span aria-hidden="true"></span></button></th>`).join('')}</tr></thead><tbody id="corpus-rows"></tbody></table></div><p class="muted corpus-table-note">Serving counts include Live source inventory after the score floor and source exclusions. Fixed Dailies and historical runs keep their original decisions.</p><dialog id="corpus-detail" aria-label="Set operations"></dialog>`;
 const body=root.querySelector('#corpus-rows'),dialog=root.querySelector('#corpus-detail');let sort='release_date',direction=-1;
 function draw(){const search=root.querySelector('#corpus-search').value.toLowerCase(),status=root.querySelector('#corpus-filter').value,quality=root.querySelector('#corpus-quality').value;
  const rows=sets.filter(s=>(!search||`${s.set_name} ${s.set_id}`.toLowerCase().includes(search))&&(!status||(s.status||'Awaiting corpus')===status)&&(!quality||health(s)===quality)).sort((a,b)=>{const left=sort==='health'?health(a):a[sort],right=sort==='health'?health(b):b[sort];return direction*(typeof left==='number'&&typeof right==='number'?left-right:String(left??'').localeCompare(String(right??'')))||a.set_id.localeCompare(b.set_id);});
  body.innerHTML=rows.map(s=>`<tr><th scope="row"><button type="button" class="corpus-open" data-open-set="${esc(s.set_id)}">${esc(s.set_name)}<small>${esc(s.set_id.toUpperCase())}</small></button></th><td>${badge(s.status||'Awaiting corpus')}</td><td class="corpus-number">${count(s.serving_count)}</td><td class="corpus-number">${count(s.under_floor_count)}</td><td>${badge(health(s))}</td><td>${esc(s.release_date)}</td><td>${esc(s.import_status||'Retained')}</td></tr>`).join('')||'<tr><td colspan="7">No sets match these filters.</td></tr>';
  root.querySelector('#corpus-row-count').textContent=`${rows.length} of ${sets.length} sets`;
  root.querySelectorAll('[data-sort]').forEach(b=>{b.closest('th').setAttribute('aria-sort',b.dataset.sort===sort?(direction===1?'ascending':'descending'):'none');b.querySelector('span').textContent=b.dataset.sort===sort?(direction===1?' ↑':' ↓'):'';});
 }
 root.querySelectorAll('.corpus-filters input,.corpus-filters select').forEach(e=>e.addEventListener('input',draw));
 root.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{direction=sort===b.dataset.sort?-direction:1;sort=b.dataset.sort;draw();});
 body.onclick=e=>{const b=e.target.closest('[data-open-set]');if(!b)return;const s=sets.find(s=>s.set_id===b.dataset.openSet);dialog.innerHTML=setDetails(s,data);dialog.showModal();dialog.querySelector('#close-corpus-detail').onclick=()=>dialog.close();};
 dialog.onsubmit=async e=>{const form=e.target.closest('[data-status-form],[data-snapshot-form]');if(!form)return;e.preventDefault();const component=form.dataset.component,s=component?data.components.find(c=>c.set_id===form.dataset.set&&c.component_version===component):sets.find(s=>s.set_id===form.dataset.set),b=Object.fromEntries(new FormData(form));form.querySelector('button').disabled=true;
  try{if(form.matches('[data-snapshot-form]')){if(!b.sourceSnapshotId)return;await request(`/v1/admin/corpus/${s.set_id}/snapshot`,{...b,corpusVersion:data.corpus_version});}else{if(!b.status)return;await request(`/v1/admin/corpus/${s.set_id}${component?`/components/${component}`:''}/status`,{...b,oldStatus:s.status,corpusVersion:data.corpus_version});}dialog.close();await renderCorpus(root,request);root.querySelector('#corpus-status').textContent=form.matches('[data-snapshot-form]')?`${s.set_id}: source snapshot activated. Existing games are preserved.`:`${s.set_id}: ${b.status}. Existing games are preserved.`;}catch(err){let error=dialog.querySelector('.corpus-action-error');if(!error){error=document.createElement('p');error.className='error corpus-action-error';error.setAttribute('role','alert');form.after(error);}error.textContent=err.message;form.querySelector('button').disabled=false;}
 };draw();
}
