import growthWorker from './index-v4.js';

const ALLOWED_ORIGINS = new Set(['https://magic.planitnow.us', 'https://killjoy00.github.io', 'http://127.0.0.1:4173', 'http://localhost:4173']);
function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8'}})}
function cors(request){const origin=request.headers.get('origin');if(!origin||!ALLOWED_ORIGINS.has(origin))return{};return{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PATCH,OPTIONS','access-control-allow-headers':'authorization,content-type,x-pack1-auth-session','access-control-max-age':'86400',vary:'Origin'}}
function withCors(response,request){const headers=new Headers(response.headers);for(const [k,v] of Object.entries(cors(request)))headers.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function databaseHttpUrl(){const url=new URL(process.env.DATABASE_URL);const parts=url.hostname.split('.');parts[0]='api';return `https://${parts.join('.')}/sql`}
async function query(sql,params=[]){const response=await fetch(databaseHttpUrl(),{method:'POST',headers:{'content-type':'application/json','Neon-Connection-String':process.env.DATABASE_URL,'Neon-Raw-Text-Output':'true','Neon-Array-Mode':'true'},body:JSON.stringify({query:sql,params:params.map(v=>v==null?null:String(v))})});if(!response.ok)throw new Error(`Database query failed (${response.status}): ${await response.text()}`);const data=await response.json();const names=(data.fields||[]).map(f=>f.name);return{rows:(data.rows||[]).map(row=>Object.fromEntries(row.map((v,i)=>[names[i],v]))),rowCount:Number(data.rowCount||0)}}
async function sessionRow(request){const token=String(request.headers.get('x-pack1-auth-session')||'').slice(0,512);if(!token)throw Object.assign(new Error('Account session required.'),{status:401});const result=await query(`SELECT s.token,s."expiresAt" expires_at,u.id user_id,u.email,u.name FROM neon_auth.session s JOIN neon_auth."user" u ON u.id=s."userId" WHERE s.token=$1 AND s."expiresAt">now() LIMIT 1`,[token]);if(!result.rows[0])throw Object.assign(new Error('Account session expired.'),{status:401});return result.rows[0]}
async function accountSession(request){const row=await sessionRow(request);return json({user:{id:row.user_id,email:row.email,name:row.name},session:{token:row.token,expiresAt:row.expires_at}})}
async function accountSignout(request){const row=await sessionRow(request);await query('DELETE FROM neon_auth.session WHERE token=$1',[row.token]);return json({ok:true})}
async function accountDailyDates(request){const row=await sessionRow(request);const link=await query('SELECT player_id FROM account_links WHERE auth_user_id=$1::uuid',[row.user_id]);if(!link.rows[0]?.player_id)return json({dates:[]});const dates=await query('SELECT DISTINCT challenge_date::text date FROM scores WHERE player_id=$1::uuid ORDER BY date DESC LIMIT 366',[link.rows[0].player_id]);return json({dates:dates.rows.map((item)=>item.date)})}

export default{async fetch(request){try{if(request.method==='OPTIONS')return withCors(new Response(null,{status:204}),request);const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/v1/account/session')return withCors(await accountSession(request),request);if(request.method==='POST'&&url.pathname==='/v1/account/signout')return withCors(await accountSignout(request),request);if(request.method==='GET'&&url.pathname==='/v1/account/daily-dates')return withCors(await accountDailyDates(request),request);return growthWorker.fetch(request)}catch(error){console.error(error);return withCors(json({error:error?.message||'Request failed.'},Number(error?.status||500)),request)}}};
